// ============================================================
// DYNATRACE OPERATIONAL INTELLIGENCE - MOCK DATA SERVICE
// Simulates DQL results for local development and demos
// ============================================================

import {
  DynatraceProblem, OperationalMetrics, ApplicationImpact,
  RootCauseCluster, AISummary, ProblemPattern, TrendPoint,
  FilterState, WeeklySnapshot, PatternHistoryRecord,
} from '../models';
import { normaliseTitle, computeRecurrenceScore, computeOperationalImpactScore } from '../queries/dqlQueries';
import { estimateCost, calcRecurringWaste } from '../cost/CostModel';

// ── Raw problem data ──────────────────────────────────────
const RAW: DynatraceProblem[] = [
  { problemId:'P-001', title:'Response time degradation on /api/checkout',         businessTitle:'Checkout Experience Degraded',        status:'RESOLVED', severity:'PERFORMANCE',         startTime:Date.now()-172800000, endTime:Date.now()-169200000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:{entityId:'svc-001',name:'checkout-service',type:'SERVICE'}, affectedUsers:3200,  managementZones:['Production','E-Commerce'], tags:['team:checkout','tier:critical'], hasRootCause:true,  recurrenceScore:80, operationalImpactScore:72, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-002', title:'Response time degradation on /api/checkout',         businessTitle:'Checkout Experience Degraded',        status:'RESOLVED', severity:'PERFORMANCE',         startTime:Date.now()-86400000,  endTime:Date.now()-83400000,  duration:50,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:{entityId:'svc-001',name:'checkout-service',type:'SERVICE'}, affectedUsers:2800,  managementZones:['Production'],              tags:['team:checkout','tier:critical'], hasRootCause:true,  recurrenceScore:80, operationalImpactScore:68, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-003', title:'Response time degradation on /api/checkout',         businessTitle:'Checkout Experience Degraded',        status:'OPEN',     severity:'PERFORMANCE',         startTime:Date.now()-7200000,                                 duration:undefined, impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:undefined,                                                    affectedUsers:1900,  managementZones:['Production'],              tags:['team:checkout','tier:critical'], hasRootCause:false, recurrenceScore:80, operationalImpactScore:65, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-004', title:'High failure rate on payment-gateway service',        businessTitle:'Payment Processing Failures',         status:'RESOLVED', severity:'ERROR',               startTime:Date.now()-259200000, endTime:Date.now()-252000000, duration:120, impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'},{entityId:'app-002',name:'MobileApp',type:'APPLICATION'}], rootCauseEntity:{entityId:'svc-002',name:'payment-gateway',type:'SERVICE'}, affectedUsers:5600,  managementZones:['Production'],              tags:['team:payments','tier:critical'],  hasRootCause:true,  recurrenceScore:80, operationalImpactScore:88, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-005', title:'High failure rate on payment-gateway service',        businessTitle:'Payment Processing Failures',         status:'RESOLVED', severity:'ERROR',               startTime:Date.now()-172800000, endTime:Date.now()-167400000, duration:90,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:undefined,                                                    affectedUsers:4200,  managementZones:['Production'],              tags:['team:payments','tier:critical'],  hasRootCause:false, recurrenceScore:80, operationalImpactScore:80, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-006', title:'High failure rate on payment-gateway service',        businessTitle:'Payment Processing Failures',         status:'RESOLVED', severity:'ERROR',               startTime:Date.now()-43200000,  endTime:Date.now()-39600000,  duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:{entityId:'db-001',name:'payments-db',type:'SERVICE'},       affectedUsers:3100,  managementZones:['Production'],              tags:['team:payments','tier:critical'],  hasRootCause:true,  recurrenceScore:80, operationalImpactScore:74, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-007', title:'CPU spike on inventory-service pod',                  businessTitle:'Inventory System Performance Issue',  status:'RESOLVED', severity:'RESOURCE_CONTENTION', startTime:Date.now()-345600000, endTime:Date.now()-344700000, duration:15,  impactedEntities:[{entityId:'svc-003',name:'inventory-service',type:'SERVICE'}],       rootCauseEntity:undefined,                                                    affectedUsers:0,     managementZones:['Production'],              tags:['team:inventory'],                hasRootCause:false, recurrenceScore:100,operationalImpactScore:28, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-008', title:'CPU spike on inventory-service pod',                  businessTitle:'Inventory System Performance Issue',  status:'RESOLVED', severity:'RESOURCE_CONTENTION', startTime:Date.now()-302400000, endTime:Date.now()-301500000, duration:15,  impactedEntities:[{entityId:'svc-003',name:'inventory-service',type:'SERVICE'}],       rootCauseEntity:undefined,                                                    affectedUsers:0,     managementZones:['Production'],              tags:['team:inventory'],                hasRootCause:false, recurrenceScore:100,operationalImpactScore:28, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-009', title:'CPU spike on inventory-service pod',                  businessTitle:'Inventory System Performance Issue',  status:'RESOLVED', severity:'RESOURCE_CONTENTION', startTime:Date.now()-216000000, endTime:Date.now()-215100000, duration:15,  impactedEntities:[{entityId:'svc-003',name:'inventory-service',type:'SERVICE'}],       rootCauseEntity:undefined,                                                    affectedUsers:0,     managementZones:['Production'],              tags:['team:inventory'],                hasRootCause:false, recurrenceScore:100,operationalImpactScore:28, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-010', title:'CPU spike on inventory-service pod',                  businessTitle:'Inventory System Performance Issue',  status:'OPEN',     severity:'RESOURCE_CONTENTION', startTime:Date.now()-3600000,                                 duration:undefined, impactedEntities:[{entityId:'svc-003',name:'inventory-service',type:'SERVICE'}],       rootCauseEntity:undefined,                                                    affectedUsers:0,     managementZones:['Production'],              tags:['team:inventory'],                hasRootCause:false, recurrenceScore:100,operationalImpactScore:32, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-011', title:'Service unavailability: auth-service',                businessTitle:'Login & Authentication Outage',       status:'RESOLVED', severity:'AVAILABILITY',         startTime:Date.now()-432000000, endTime:Date.now()-428400000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'},{entityId:'app-003',name:'AdminPortal',type:'APPLICATION'}], rootCauseEntity:{entityId:'svc-004',name:'auth-service',type:'SERVICE'}, affectedUsers:12000, managementZones:['Production','Critical'],    tags:['team:auth','tier:critical'],     hasRootCause:true,  recurrenceScore:20, operationalImpactScore:95, cloud:'aws', region:'us-east-1',      isKubernetes:false },
  { problemId:'P-012', title:'Memory leak detected: recommendation-engine',         businessTitle:'Personalisation Engine Degraded',     status:'RESOLVED', severity:'RESOURCE_CONTENTION', startTime:Date.now()-518400000, endTime:Date.now()-504000000, duration:240, impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:{entityId:'svc-005',name:'recommendation-engine',type:'SERVICE'}, affectedUsers:800,  managementZones:['Production'],              tags:['team:ml','tier:standard'],       hasRootCause:true,  recurrenceScore:20, operationalImpactScore:55, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-013', title:'Slow database queries detected: product-catalog-db',  businessTitle:'Product Search Performance Impact',   status:'RESOLVED', severity:'PERFORMANCE',         startTime:Date.now()-604800000, endTime:Date.now()-601200000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'},{entityId:'app-002',name:'MobileApp',type:'APPLICATION'}], rootCauseEntity:{entityId:'db-002',name:'product-catalog-db',type:'SERVICE'}, affectedUsers:4500, managementZones:['Production'],             tags:['team:catalog','tier:critical'],  hasRootCause:true,  recurrenceScore:40, operationalImpactScore:70, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-014', title:'Slow database queries detected: product-catalog-db',  businessTitle:'Product Search Performance Impact',   status:'RESOLVED', severity:'PERFORMANCE',         startTime:Date.now()-360000000, endTime:Date.now()-356400000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:{entityId:'db-002',name:'product-catalog-db',type:'SERVICE'}, affectedUsers:3800, managementZones:['Production'],             tags:['team:catalog','tier:critical'],  hasRootCause:true,  recurrenceScore:40, operationalImpactScore:66, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-015', title:'External API timeout: shipping-provider',             businessTitle:'Order Shipping Estimate Delays',      status:'RESOLVED', severity:'ERROR',               startTime:Date.now()-691200000, endTime:Date.now()-687600000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:undefined,                                                    affectedUsers:2100,  managementZones:['Production'],              tags:['team:fulfillment'],              hasRootCause:false, recurrenceScore:20, operationalImpactScore:50, cloud:'aws', region:'ap-southeast-2', isKubernetes:false },
  { problemId:'P-016', title:'High GC pause rate: search-indexer',                  businessTitle:'Search & Discovery Performance Drop', status:'RESOLVED', severity:'PERFORMANCE',         startTime:Date.now()-129600000, endTime:Date.now()-126000000, duration:60,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'},{entityId:'app-002',name:'MobileApp',type:'APPLICATION'}], rootCauseEntity:{entityId:'svc-006',name:'search-indexer',type:'SERVICE'}, affectedUsers:7200, managementZones:['Production'],             tags:['team:search'],                   hasRootCause:true,  recurrenceScore:20, operationalImpactScore:78, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-017', title:'Network latency: cross-region replication',           businessTitle:'Regional Connectivity Issue',         status:'OPEN',     severity:'PERFORMANCE',         startTime:Date.now()-1800000,                                 duration:undefined, impactedEntities:[{entityId:'app-002',name:'MobileApp',type:'APPLICATION'}],           rootCauseEntity:undefined,                                                    affectedUsers:320,   managementZones:['Production'],              tags:['team:platform'],                 hasRootCause:false, recurrenceScore:20, operationalImpactScore:42, cloud:'aws', region:'us-east-1',      isKubernetes:false },
  { problemId:'P-018', title:'Container OOMKilled: session-service',                businessTitle:'User Session Interruption',           status:'RESOLVED', severity:'AVAILABILITY',         startTime:Date.now()-388800000, endTime:Date.now()-387000000, duration:30,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:undefined,                                                    affectedUsers:1500,  managementZones:['Production'],              tags:['team:auth'],                     hasRootCause:false, recurrenceScore:40, operationalImpactScore:58, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-019', title:'Container OOMKilled: session-service',                businessTitle:'User Session Interruption',           status:'RESOLVED', severity:'AVAILABILITY',         startTime:Date.now()-259200000, endTime:Date.now()-257400000, duration:30,  impactedEntities:[{entityId:'app-001',name:'ShopApp',type:'APPLICATION'}],             rootCauseEntity:undefined,                                                    affectedUsers:1200,  managementZones:['Production'],              tags:['team:auth'],                     hasRootCause:false, recurrenceScore:40, operationalImpactScore:54, cloud:'aws', region:'ap-southeast-2', isKubernetes:true  },
  { problemId:'P-020', title:'Disk I/O saturation: log-aggregator',                 businessTitle:'Platform Logging Disruption',         status:'RESOLVED', severity:'RESOURCE_CONTENTION', startTime:Date.now()-475200000, endTime:Date.now()-471600000, duration:60,  impactedEntities:[{entityId:'svc-007',name:'log-aggregator',type:'SERVICE'}],          rootCauseEntity:{entityId:'svc-007',name:'log-aggregator',type:'SERVICE'},   affectedUsers:0,     managementZones:['Production'],              tags:['team:platform'],                 hasRootCause:true,  recurrenceScore:20, operationalImpactScore:25, cloud:null,  region:undefined,            isKubernetes:false },
];

// ── Filter utility ─────────────────────────────────────────
function applyFilters(problems: DynatraceProblem[], filters: FilterState): DynatraceProblem[] {
  return problems.filter(p => {
    if (filters.severities.length && !filters.severities.includes(p.severity)) return false;
    if (filters.statuses.length   && !filters.statuses.includes(p.status))     return false;
    if (filters.tags.length       && !filters.tags.some(t => p.tags.includes(t))) return false;
    if (filters.managementZones.length && !filters.managementZones.some(z => p.managementZones.includes(z))) return false;
    if (filters.applications.length) {
      const hasApp = p.impactedEntities.some(e => filters.applications.includes(e.name));
      if (!hasApp) return false;
    }
    if (filters.searchText) {
      if (!p.title.toLowerCase().includes(filters.searchText.toLowerCase())) return false;
    }
    return true;
  });
}

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ── Public API — mirrors DynatraceService interface ────────

export const MockDataService = {

  async getProblems(filters: FilterState): Promise<DynatraceProblem[]> {
    await delay(400);
    return applyFilters(RAW, filters);
  },

  async getWeeklySnapshots(): Promise<WeeklySnapshot[]> {
    await delay(300);
    return [
      { week:'Apr 7',  weekStart:Date.now()-7*7*86400000, totalProblems:22, avgMTTR:82, recurringCount:12, missingRCA:43, estimatedCost:89400, noisyAlerts:8 },
      { week:'Apr 14', weekStart:Date.now()-6*7*86400000, totalProblems:20, avgMTTR:76, recurringCount:11, missingRCA:39, estimatedCost:81200, noisyAlerts:7 },
      { week:'Apr 21', weekStart:Date.now()-5*7*86400000, totalProblems:19, avgMTTR:71, recurringCount:10, missingRCA:34, estimatedCost:74800, noisyAlerts:6 },
      { week:'Apr 28', weekStart:Date.now()-4*7*86400000, totalProblems:18, avgMTTR:65, recurringCount:8,  missingRCA:29, estimatedCost:63100, noisyAlerts:5 },
      { week:'May 5',  weekStart:Date.now()-3*7*86400000, totalProblems:17, avgMTTR:61, recurringCount:7,  missingRCA:24, estimatedCost:58700, noisyAlerts:4 },
      { week:'May 12', weekStart:Date.now()-2*7*86400000, totalProblems:16, avgMTTR:55, recurringCount:6,  missingRCA:21, estimatedCost:49200, noisyAlerts:3 },
      { week:'May 19', weekStart:Date.now()-1*7*86400000, totalProblems:15, avgMTTR:51, recurringCount:5,  missingRCA:18, estimatedCost:41800, noisyAlerts:2 },
      { week:'May 27', weekStart:Date.now(),              totalProblems:20, avgMTTR:48, recurringCount:5,  missingRCA:18, estimatedCost:38600, noisyAlerts:2 },
    ];
  },

  async getPatternHistory(): Promise<PatternHistoryRecord[]> {
    await delay(300);
    return [
      { id:'ph-checkout', title:'Checkout Experience Degraded',       technicalTitle:'Response time degradation on /api/checkout',        firstFlagged:Date.now()-50*86400000, severity:'PERFORMANCE',         recommendation:'FIX_ROOT_CAUSE',    ticket:{ ticketId:'INC0044102', url:'https://your-instance.service-now.com/incident/INC0044102', status:'in_progress', assignee:'James T.',  team:'Platform Engineering',  openedAt:Date.now()-6*86400000,  resolvedAt:undefined }, occurrencesByWeek:[2,3,3,2,3,2,2,3], costByWeek:[7200,8400,7800,6900,8100,7200,6800,8100], isRegressed:false, rca:'checkout-service'      },
      { id:'ph-payment',  title:'Payment Processing Failures',         technicalTitle:'High failure rate on payment-gateway service',       firstFlagged:Date.now()-50*86400000, severity:'ERROR',               recommendation:'FIX_ROOT_CAUSE',    ticket:{ ticketId:'INC0043821', url:'https://your-instance.service-now.com/incident/INC0043821', status:'in_progress', assignee:'Arun M.',   team:'Payments Engineering', openedAt:Date.now()-21*86400000, resolvedAt:undefined }, occurrencesByWeek:[3,3,3,2,3,3,2,3], costByWeek:[38000,41000,36000,29000,38000,35000,32000,38000], isRegressed:false, rca:'payments-db'          },
      { id:'ph-inventory',title:'Inventory CPU Spikes',                technicalTitle:'CPU spike on inventory-service pod',                 firstFlagged:Date.now()-42*86400000, severity:'RESOURCE_CONTENTION', recommendation:'DISABLE_ALERT',     ticket:{ ticketId:'INC0043955', url:'https://your-instance.service-now.com/incident/INC0043955', status:'resolved',    assignee:'Sarah K.',  team:'Platform Engineering',  openedAt:Date.now()-35*86400000, resolvedAt:Date.now()-14*86400000 }, occurrencesByWeek:[4,4,3,2,1,0,0,0], costByWeek:[564,564,423,282,141,0,0,0], isRegressed:false, rca:'inventory-service'    },
      { id:'ph-session',  title:'User Session Interruption',           technicalTitle:'Container OOMKilled: session-service',              firstFlagged:Date.now()-35*86400000, severity:'AVAILABILITY',         recommendation:'INVESTIGATE_FIRST', ticket:null,                                                                                                                                                                                                                                                         occurrencesByWeek:[0,2,1,2,2,1,2,2], costByWeek:[0,4800,2400,4800,4800,2400,4800,4800], isRegressed:false, rca:null                   },
      { id:'ph-catalog',  title:'Product Search Performance Impact',   technicalTitle:'Slow database queries: product-catalog-db',         firstFlagged:Date.now()-56*86400000, severity:'PERFORMANCE',         recommendation:'FIX_ROOT_CAUSE',    ticket:{ ticketId:'INC0043310', url:'https://your-instance.service-now.com/incident/INC0043310', status:'resolved',    assignee:'Priya S.',  team:'Catalog Engineering',   openedAt:Date.now()-49*86400000, resolvedAt:Date.now()-21*86400000 }, occurrencesByWeek:[2,2,1,0,0,0,0,0], costByWeek:[8200,8200,4100,0,0,0,0,0], isRegressed:false, rca:'product-catalog-db'  },
      { id:'ph-auth',     title:'Login & Authentication Outage',        technicalTitle:'Service unavailability: auth-service',              firstFlagged:Date.now()-28*86400000, severity:'AVAILABILITY',         recommendation:'FIX_ROOT_CAUSE',    ticket:{ ticketId:'INC0044089', url:'https://your-instance.service-now.com/incident/INC0044089', status:'closed',      assignee:'James T.',  team:'Auth Engineering',      openedAt:Date.now()-28*86400000, resolvedAt:Date.now()-7*86400000  }, occurrencesByWeek:[1,0,0,1,0,0,0,1], costByWeek:[28000,0,0,28000,0,0,0,28000], isRegressed:true,  rca:'auth-service'         },
    ];
  },
};
